language: csharp
solution: Easly-Controller.sln

script:
- msbuild Easly-Controller.sln /p:Configuration=Travis

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: ./Easly-Controller/bin/x64/Travis
  target_branch: gh-pages
  email: "github-pages-deploy@travis-ci.org"
  on:
    branch: master

