codecov:
  notify:
    require_ci_to_pass: yes

coverage:
  precision: 2
  round: down
  range: "70...100"

  status:
    project: yes
    patch: yes
    changes: no

parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: no
      macro: no

comment:
  layout: "header, diff"
  behavior: default
  require_changes: no

ignore:
  - Easly-Controller/02-Writeable/Index/Browsing/Collection/Writeable_BrowsingBlockNodeIndex.cs
  - Easly-Controller/02-Writeable/Index/Browsing/Collection/Writeable_BrowsingCollectionNodeIndex.cs
  - Easly-Controller/02-Writeable/Inner/Collection/Writeable_CollectionInner.cs
  - Easly-Controller/02-Writeable/Inner/Single/Writeable_SingleInner.cs
  - Easly-Controller/02-Writeable/Inner/Writeable_Inner.cs
  - Easly-Controller/02-Writeable/State/Writeable_NodeState.cs
  - Easly-Controller/02-Writeable/StateView/Writeable_NodeStateView.cs
  - Easly-Controller/03-Frame/Controller/Operations/Frame_Operation.cs
  - Easly-Controller/03-Frame/Controller/Operations/Frame_Insert_Operation.cs
  - Easly-Controller/03-Frame/Controller/Operations/Frame_Remove_Operation.cs
  - Easly-Controller/04-Focus
  - Easly-Controller/Controller/TypeMarkupExtension.cs
